version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    assignees:
      - albabar
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - albabar
